FROM eclipse-temurin:17-jdk-alpine

# Install stress-ng (requires root)
USER root
RUN apk add --no-cache stress-ng iproute2

# Change directory
WORKDIR /app

# Download the OTel Java Agent
ARG OTEL_AGENT_VERSION=2.8.0
ARG OTEL_AGENT_JAR=/app/opentelemetry-javaagent.jar
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OTEL_AGENT_VERSION}/opentelemetry-javaagent.jar $OTEL_AGENT_JAR

# Copy war file and start-app.sh script
COPY target/websocket-service-0.0.1-SNAPSHOT.war websocket-service.war

# Run app
ENTRYPOINT ["sh","-c","java -javaagent:opentelemetry-javaagent.jar -Dspring.config.location=$CONFIG_PATH -jar websocket-service.war"]

# Expose port 8084
EXPOSE 8084